export const dockerOciRouteManifest = [
  'index',
  'guide/source-to-container',
  'guide/container-to-kubernetes',
  'concepts/docker-architecture',
  'concepts/image-model',
  'concepts/container-model',
  'build/dockerfile',
  'build/buildkit-cache',
  'build/multi-platform-builds',
  'runtime/process-lifecycle',
  'runtime/networking',
  'runtime/storage',
  'runtime/compose',
  'oci/specifications',
  'operations/security',
  'operations/troubleshooting',
  'reference/command-map',
] as const
